### ISSUE TITLE
Rip down master branch with a readme

### ISSUE THREAD

**Issue by tisonkun** [apache/apache-website-template#18]
According to https://lists.apache.org/thread/tvry49gdclqqdtdcgk0x9hnl18vlxnm8, we'd host multiple templates in different branches, leave the default branch a readme only branch with redirections and docs.

Also, we'd declare that open-ended discussion of this repo SHOULD go to dev@community.a.o.

**Comment by bdelacretaz** [comment]
> a readme only branch with redirections and docs.

and links to existing examples such as [ASF websites powered by Hugo](https://github.com/search?q=topic%3Ahugo+org%3Aapache&type=Repositories), [JBake](https://github.com/search?q=topic%3Ajbake+org%3Aapache&type=Repositories) and other such technologies. We should encourage projects to add the relevant GitHub topics to their repositories so that they can be found by such queries.
